name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  #- pandas=1.1.4
  #- pandas=2.0.3
  - pandas=2.1.3
  - pip=20.3.3
  #- mlflow=1.14.1
  #- mlflow=1.8.0
  - mlflow=2.2.2
  - scikit-learn=0.24.1
  #- scikit-learn=1.3.2
  #- numpy=1.21.6
  - numpy=1.23.4
  #- numpy==1.19.5
  #- scipy=1.6.0
  - scipy=1.11.3
  - pip:
    - wandb==0.10.31
    - cloudpickle==2.1.0
    #- cloudpickle==3.0.0
    #- cloudpickle==2.2.1
    - protobuf==4.24.4
    #- git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
    - git+https://github.com/mikethwolff/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components